language: ruby
rvm:
 - 2.2.1
script: bundle exec rake github
notifications:
  email:
    recipients:
    - anurag@mohanty.io
    on_success:
    - always|never|change
    on_failure:
    - always|never|change
