language: ruby
rvm:
 - 2.5.1
before_install:
  - bundle update --bundler
  - sudo apt-get install -y libxrender1 libpng16-16 libssl1.0.0 libssl-dev
  - cd /lib/x86_64-linux-gnu && sudo ln -s libssl.so.1.0.0 libssl.so.10 && sudo ln -s libcrypto.so.1.0.0 libcrypto.so.10
  - cd ~/tevren/resume
script: bundle exec rake github
env:
  - secure: "AHvBP7KBW1YHwTUcwchZ9+pido8zHIU+KGc53xIkn74jHhb9dyWiaJ4aw3dYxAmoIgR8OvsXNcthU6+oOTaD0ReTUTTrFJfBAzimtbb+AaHzR4sqQzfmaDJkQmoNnjtELprGG1enx4vPVvQ/Vk4SeU9u20fESsC7jJLwm9eYb5YJmmUKm3sdZNO9RMg0FAfbYsd8aqeNVDWRUPSMNgg4ic4w3LbgxhGbgjNEoVUsz2Akw/ZuMr7J9Sin4uQWYTC/Mwc8OmEL0pdDLSA6c9NLW8ub8TporMg/mkoeZnJISwkuLWe8XN1oJAVp72mVOuNLDmA88660gjpDgyVGmbxMgBlrDkc0Gc9QQ+6MI8XEq8NVyW67JuB/wNhA1OzPOyEYPB8PbfaR9JXYZ+wcTCGthoMU7cIcH05RDHJ9tuIQ4rbWnM9v63BVjkI7Pyt2G7fFYBd3w8EBxs1MIfjVNLxsD1t+pad60vMRoiykSVOQzE5f9Ncoi/P7W3gOqfAnjGLEJWjxo93FK+SD2QV4D1w3F2iWsjpR7ZvJshTdjwijaauLURbKxVG5kzylLUXghMNzJrkzr5NSDclJ/bHjvC3HSBotKAHKPJBLvTeopYALmCug4Yd2KudHpi0wr86urwYR/R0pDohQvZNrmZlT02WuvQbHg78P4jatb5I1nrPvV7w="
notifications:
  email:
    recipients:
    - anurag@mohanty.io
    on_success:
    - always|never|change
    on_failure:
    - always|never|change
