language: ruby
rvm:
 - 2.2.1
script: bundle exec rake github
env:
  - secure: "dxskzJq7S0C3O48XYO/QVDtlhPVSRBiKCnEpfIh0aODRY8kwL1oo8ACp8pmHfIrbNBZ5OR0bgUdRskfs5deLLyUnJGveG23AUoKNvE64/ak9OFhjhbLnUPac46tv/xsD+sO1Kf72Od9bt0mcrn6DRnRrlxPiWpshmgmFN3QuF9Xf/l/AEqkLqE9f+L7wq6k0qxmNX4v7B2S6a+G5rafZAJiWIuO0HXD7q1r4OJD8wSx2/K2ytGWMhEnAgAWRAXeuYg9pIxqo5zWa5dxCg3JiGipZaPNoFUmR5tPMOTM2rR0c7O7KbrAn2yAPOLwGYSQQ1UG9GwMl0BtTcAVfouTOp9VcCXROVb69XZ2NSrTg3dY/F/S7neb87lsE3xmn/Pq37I6KdF0m3Ss1Z4qVrBGYq2ZPESFqhVmvx3U/bvHvULbfgwPlqw2nqNT3nqSGMrcwp3Qh2BpdvjXgig55Hx+XL+9D41FvEdLPt0MK8dswJJ6Sm0371Y8lK8zxayEKNtcWyLgW1YO37toUqBVw3aUaVEHPjDViM6vlmOS1otDwyAcQApFAqXUxZP43BE895/ZtX/rsUALJAErTBIoWqb7cJUPjCNSkUz56BGyibE5tirayylASnb+Wf0YQYVoynfLTwwkKkPuYS7WKtx32gbxbKeje1qcIj84XsvtH/YaT3jY="
notifications:
  email:
    recipients:
    - anurag@mohanty.io
    on_success:
    - always|never|change
    on_failure:
    - always|never|change
